benchmark_root: /opt/LIBERO/libero/libero
bddl_files: /opt/LIBERO/libero/libero/bddl_files
init_states: /opt/LIBERO/libero/libero/init_files
datasets: /artifacts/datasets/libero
assets: /opt/LIBERO/libero/libero/assets
